name: Deploy My Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.12.0

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-avzr --exclude .user.ini"
          SOURCE: "./dist/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: "root"
          TARGET: '/www/wwwroot/preview.panel.chmlfrp.cn'
          EXCLUDE: "/node_modules/ .user.ini"
